### ISSUE TITLE
Friendster dataset preprocess

### ISSUE THREAD

**Issue by ttaliacc** [gsampler9/gSampler#10]
Hi, 

I'm currently trying to reproduce some of your experiments with gsampler-artifact-evaluation, specifically using the ogbn-papers100M and Friendster datasets. While my results for ogbn-papers100M are quite similar to what you reported in Figure 9, the results for Friendster differ significantly. I understand that there may be configuration differences, but I'd like to double-check the preprocessing steps you used, particularly for Friendster.

The preprocessing of the Friendster dataset has proven to be a bit tricky for me. Since it's undirected, when generating the DGL adjacency matrix (friendster_adj.bin), I added each edge twice to the graph—once with the source as the origin and once with the destination as the origin. Below is a snippet of the preprocessing code I used:
```
# Read the CSV file in chunks
for chunk in pd.read_csv(edges_file, chunksize=chunk_size):
    src_ids = chunk['src_id'].tolist()
    dst_ids = chunk['dst_id'].tolist()

    for src, dst in zip(src_ids, dst_ids):
        all_src_ids.append(src)
        all_dst_ids.append(dst)
        all_src_ids.append(dst)
        all_dst_ids.append(src)
# Convert lists to tensors
src_tensor = torch.tensor(all_src_ids)
dst_tensor = torch.tensor(all_dst_ids)

# Create the DGL graph
g = dgl.graph((src_tensor, dst_tensor))
```

Additionally, I noticed that the original Friendster edges.txt file contains node IDs that aren't within the expected range of (0, #nodes). To address this, I relabeled the node IDs so that they are all within the valid range, allowing me to use `DGL.graph` to generate the adjacency matrix.

It will be great if you could verify whether my preprocessing approach aligns with your method. If possible, could you share any additional details on how you handled the preprocessing of the Friendster dataset?

**Comment by Liu-rj** [comment]
Thanks for your interest in our work. I have just pushed the dataset preprocessing code previously used in our artifact. You can check out and try `examples/utils/gen_graph_from_txt.py`.

Since friendster txt is undirected, you need to set the `--to-bidirected` flag along with the specified txt file path. For livejournal, the txt is already in directed format so you don't need to pass the `--to-bidirected` flag.

**Comment by ttaliacc** [comment]
Thank you. This helps a lot!

**Comment by ttaliacc** [comment]
Hi, thanks again for providing the preprocessing code.

I tried running the preprocessing on the Friendster dataset, but I encountered a memory issue. 

```
python gen_graph_from_txt.py --txt-path="/data/friendster/com-friendster.ungraph.txt" --to-bidirected
construct the graph
Converting to bi-directional...
Killed
```

The machine I'm using has 250GB of RAM. Do you know the approximate memory required to process the Friendster dataset? Alternatively, could you share the machine configuration you used to successfully process it?

**Comment by Liu-rj** [comment]
We use the AWS p3.16xlarge instance which has about 488GB memory to preprocess Friendster graph.

**Comment by ttaliacc** [comment]
Hi, I tried with larger machine, and it worked. Thanks for your help.
