### ISSUE TITLE
OSError: /root/share/gsampler/python/gs/libgs.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by LukeLIN-web** [gsampler9/gSampler#4]
I installed it according to the guidance.
There seems to be no error. But I cannot import it. 

```
>>> import gs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/share/gsampler/python/gs/__init__.py", line 6, in <module>
    torch.classes.load_library(so_path)
  File "/opt/conda/lib/python3.10/site-packages/torch/_classes.py", line 51, in load_library
    torch.ops.load_library(path)
  File "/opt/conda/lib/python3.10/site-packages/torch/_ops.py", line 573, in load_library
    ctypes.CDLL(path)
  File "/opt/conda/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /root/share/gsampler/python/gs/libgs.so: cannot open shared object file: No such file or directory
>>> print(gs.package_path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'gs' is not defined
```

**Comment by LukeLIN-web** [comment]
`cp libgs.so /root/share/gsampler/python/gs/ ` solves it .

**Comment by LukeLIN-web** [comment]
I upgrade cpp to version 9.4.0, and reinstall according to guidance. It can work.

**Comment by WWWzq-01** [comment]
> `cp libgs.so /root/share/gsampler/python/gs/ ` but it hang on beginning of program.

Hello, may I ask where the parent directory of libgs.so is located?

**Comment by gpzlx1** [comment]
> > `cp libgs.so /root/share/gsampler/python/gs/ ` but it hang on beginning of program.
> 
> Hello, may I ask where the parent directory of libgs.so is located?

Hi there! After you've executed the CMake and build process, the resulting libgs.so library should be located in the build directories.

**Comment by WWWzq-01** [comment]
> > > `cp libgs.so /root/share/gsampler/python/gs/ ` but it hang on beginning of program.
> > 
> > 
> > Hello, may I ask where the parent directory of libgs.so is located?
> 
> Hi there! After you've executed the CMake and build process, the resulting libgs.so library should be located in the build directories.

Thank you! I find the libgs.so library and copied it to the corresponding directory. Then, I  import gs successfully.
