### ISSUE TITLE
Number of Sample of the Evaluation Results in the Paper

### ISSUE THREAD

**Issue by EstherBear** [gsampler9/gSampler#5]
Hi there,

I've read the NextDoor paper and your paper. Great work!

I'm curious about the number of sample of the evaluation results in the paper but I couldn't find it. Would you mind provide me this parameter?

Thanks!

**Comment by gpzlx1** [comment]
For the 7 graph sampling algorithms, their hyper-parameters (number of layers, batch size and fanout) follow the author code of their original papers and examples released by well-known graph learning frameworks (i.e., DGL and PyG). 

Here are the details:
![微信截图_20231112211154](https://github.com/gsampler9/gSampler/assets/33480480/a046318f-c25d-453a-a611-4f24c5a9fbed)

**Comment by EstherBear** [comment]
Thank you for your reply!

**Comment by EstherBear** [comment]
Thank you for your reply!
