### ISSUE TITLE
Some variable names in libtorch's logging and glog are conflicting.

### ISSUE THREAD

**Issue by PoplarZhu** [gsampler9/gSampler#7]
### version
Pytorch: 1.13.1
Cuda: 11.7
CMAKE: 3.16.3

make -j failed:

I have seen a lot of similar bugs in pytorch issues and there is no good solution. It seems to be due to a link conflict between torch and glog.Have you encountered similar problems?

/usr/local/miniconda3/envs/gsampler/lib/python3.9/site-packages/torch/include/c10/util/logging_is_not_google_glog.h:133: note: this is the location of the previous definition
  133 | #define DLOG(n)                   \
      | 
In file included from /gSampler/src/cuda/batch/../../logging.h:29,
                 from /gSampler/src/cuda/batch/../utils.h:6,
                 from /gSampler/src/cuda/batch/list_sampling_probs.cu:5:
/gSampler/build/third_party/glog/glog/logging.h:1193: warning: "DLOG" redefined
 1193 | #define DLOG(severity)  \

**Comment by gpzlx1** [comment]
Hello, thank you for the bug report.

The issue stems from both glog and torch defining some identical macros (such as DLOG, LOG, and others). One straightforward solution is to undefine one before including the other. This is precisely what [logging.h](./src/logging.h) accomplishes.

It appears that PyTorch seems introduce a new macro `DLOG`, which causes compilation to fail. I've created a new branch [fix_dlog](https://github.com/gsampler9/gSampler/tree/fix_dlog) to address this issue. Feel free to try it out. It has successfully resolved the problem for me using PyTorch version 2.2 and CUDA version 12.3.
